customer_analysis_task:
  description: >
    Analyze the customer's basic information to extract critical insights that
    might be useful for qualifying them and deciding how to tailor the message.

    This includes understanding what segment they belong to, how likely they
    are to benefit from {product_service}, and if anything about their market
    or role raises flags or opportunities.

    Details:
    - Client Name: {client_name}
    - Client Market Segment Intro: {client_market_segment_intro}
    - Product/Service to Present: {product_service}
    - Your Company Name: {your_company_name}
    - Your Name: {your_name}
    - Task Prompt: {task_prompt}
  expected_output: >
    Summarize your analysis of this customer. Focus on whether they seem like a good fit, 
    any useful insights from their market segment, and how we might position our product 
    to them. Short or vague info might be a yellow flag.

pitch_email_task:
  description: >
    Based on the customer analysis and basic CRM input, write a cold outreach email
    to introduce {product_service} to the customer.

    The email should be short, human, and personalized based on the customer's market
    segment and role. Don't oversell—focus on helping and highlighting the relevance
    of our product.

    Inputs:
    - Client Name: {client_name}
    - Client Market Segment Intro: {client_market_segment_intro}
    - Product/Service to Present: {product_service}
    - Your Company Name: {your_company_name}
    - Your Name: {your_name}
    - Task Prompt: {task_prompt}
  expected_output: >
    A JSON object with the subject and body of the email.

    {
      "subject": "Intro to {product_service} — A solution for {client_name}",
      "body": "<personalized email body>"
    }

email_formatting_task:
  description: >
    Format the outreach email into a clean structure. Ensure the email is
    easy to read, spaced properly, and polished for professionalism.

    The subject and body of the email will be generated by the previous task
    (pitch_email_task) and will be provided as inputs for this task.

  expected_output: >
    A final version of the email including:
    - Clear subject line
    - Email body formatted with greeting, main message, and sign-off
    - Clean line breaks and whitespace